services: 
  app: 
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=testdb
    depends_on: 
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data:
